In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('data/nomes_logradouros.parquet')

In [3]:
df.head()

   codlog cd_tipo_logradouro        nm_logradouro
0  000027                  R      COUTO DE CALVAO
1  000035                  R             PIROFONE
2  000043                  R          ABACATEIROS
3  000051                  R  ABADIA DOS DOURADOS
4  000060                  R            ABADIANIA

In [4]:
df.shape

(50690, 3)

In [6]:
df = pd.read_parquet('data/segmentos_logradouros.parquet')

In [7]:
df.head()

,codlog,cd_identificador,cd_numero_inicial_par,cd_numero_final_par,cd_numero_inicial_impar,cd_numero_final_impar
0,000027,222880,0,62,1,63
1,000035,201562,0,124,1,125
2,000043,120796,0,78,1,79
3,000043,120797,78,90,79,91
4,000043,120798,90,164,91,165

In [8]:
df.shape

(192077, 6)

In [9]:
df = pd.read_parquet('data/enderecos_fiscais.parquet')

In [10]:
df.head()

,cd_identificador,cd_setor_fiscal,cd_tipo_quadra,cd_quadra_fiscal,cd_condominio,cd_tipo_lote,cd_lote,cd_digito_sql,cd_logradouro,nm_logradouro_completo,cd_numero_porta,tx_complemento_endereco
0,1957324,027,F,026,00,F,0019,0,048046,R CESARIO ALVIM,716,NaN
1,1957325,027,F,026,00,F,0020,4,048046,R CESARIO ALVIM,720,BELENZINHO
2,1957326,030,F,131,00,F,0011,7,020583,R ARAPANEMA,57,NaN
3,1957327,018,F,070,00,F,0018,4,031216,R BENEDITA SA BARBOSA,20,NaN
4,1957328,016,F,102,08,F,0000,NaN,186201,R PROF TAMANDARE TOLEDO,104,NaN

In [12]:
df.shape

(1681353, 12)