In [2]:
import pandas as pd

In [2]:
df = pd.read_parquet('data/nomes_logradouros.parquet')

In [3]:
df.head()

   codlog cd_tipo_logradouro        nm_logradouro
0  000027                  R      COUTO DE CALVAO
1  000035                  R             PIROFONE
2  000043                  R          ABACATEIROS
3  000051                  R  ABADIA DOS DOURADOS
4  000060                  R            ABADIANIA

In [4]:
df.shape

(50690, 3)

In [4]:
pd.read_parquet('data/tipos_logradouro_cache.parquet')

            nome_tipo cd_tipo_logradouro
0              ACESSO                 AC
1               ACESO                 AC
2             ACESSSO                 AC
3                  AC                 AC
4             ALAMEDA                 AL
...               ...                ...
6246  VJA DE PEDRESTE                 VP
6247  VIA DE P3DRESTE                 VP
6248  VIA DE PEDRESTR                 VP
6249  VIA DE PEDRESFE                 VP
6250  VIA DE PEDRESTF                 VP

[6251 rows x 2 columns]