In [2]:
import pandas as pd

In [2]:
df = pd.read_parquet('data/nomes_logradouros.parquet')

In [3]:
df.head()

   codlog cd_tipo_logradouro        nm_logradouro
0  000027                  R      COUTO DE CALVAO
1  000035                  R             PIROFONE
2  000043                  R          ABACATEIROS
3  000051                  R  ABADIA DOS DOURADOS
4  000060                  R            ABADIANIA

In [4]:
df.shape

(50690, 3)

In [4]:
pd.read_parquet('data/tipos_logradouro_cache.parquet')

            nome_tipo cd_tipo_logradouro
0              ACESSO                 AC
1               ACESO                 AC
2             ACESSSO                 AC
3                  AC                 AC
4             ALAMEDA                 AL
...               ...                ...
6246  VJA DE PEDRESTE                 VP
6247  VIA DE P3DRESTE                 VP
6248  VIA DE PEDRESTR                 VP
6249  VIA DE PEDRESFE                 VP
6250  VIA DE PEDRESTF                 VP

[6251 rows x 2 columns]

In [3]:
from services.domain.logradouros_match import match_logradouro, LogradouroMatchQuery

In [5]:
q = LogradouroMatchQuery(texto="avenida paulista")

In [8]:
result = match_logradouro(q)

In [10]:
result.codlogs

['156566']

In [11]:
result.ignorou_filtro_tipo

False

In [12]:
result.logradouros

[LogradouroMatch(codlog='156566', tipo_codigo='AV', nome_logradouro='PAULISTA')]

In [14]:
result.match_nome.best_match

FuzzyMatchItem(original_string='PAULISTA', cleaned_string='PAULISTA', similarity_score=100.0, rank_position=1)

In [17]:
result.match_tipo.best_match

FuzzyMatchItem(original_string='AVENIDA', cleaned_string='AVENIDA', similarity_score=100.0, rank_position=1)

In [18]:
q = LogradouroMatchQuery(texto="rua paulista")

In [19]:
result = match_logradouro(q)

In [20]:
result.logradouros

[LogradouroMatch(codlog='156590', tipo_codigo='R', nome_logradouro='PAULISTANIA')]

In [21]:
result.match_nome.best_match

FuzzyMatchItem(original_string='PAULISTANIA', cleaned_string='PAULISTANIA', similarity_score=94.54545454545456, rank_position=1)

In [22]:
result.match_nome.cleaned_query

'PAULISTA'

In [23]:
result.match_nome.matches

[FuzzyMatchItem(original_string='PAULISTANIA', cleaned_string='PAULISTANIA', similarity_score=94.54545454545456, rank_position=1),
 FuzzyMatchItem(original_string='PAULISTANOS', cleaned_string='PAULISTANOS', similarity_score=94.54545454545456, rank_position=2),
 FuzzyMatchItem(original_string='PAULISTINHA', cleaned_string='PAULISTINHA', similarity_score=94.54545454545456, rank_position=3),
 FuzzyMatchItem(original_string='PAULINA', cleaned_string='PAULINA', similarity_score=92.14285714285715, rank_position=4),
 FuzzyMatchItem(original_string='PAULINA', cleaned_string='PAULINA', similarity_score=92.14285714285715, rank_position=5)]