In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet('data/nomes_logradouros.parquet')

In [3]:
df.head()

   codlog cd_tipo_logradouro        nm_logradouro
0  000027                  R      COUTO DE CALVAO
1  000035                  R             PIROFONE
2  000043                  R          ABACATEIROS
3  000051                  R  ABADIA DOS DOURADOS
4  000060                  R            ABADIANIA

In [4]:
df.shape

(50690, 3)

In [6]:
df = pd.read_parquet('data/segmentos_logradouros.parquet')

In [7]:
df.head()

,codlog,cd_identificador,cd_numero_inicial_par,cd_numero_final_par,cd_numero_inicial_impar,cd_numero_final_impar
0,000027,222880,0,62,1,63
1,000035,201562,0,124,1,125
2,000043,120796,0,78,1,79
3,000043,120797,78,90,79,91
4,000043,120798,90,164,91,165

In [8]:
df.shape

(192077, 6)